export const LANGUAGE_STORAGE_KEY = 'shahdara-cloud-ui-language';

const ROMAN_URDU = Object.freeze({
  'Skip to main content': 'Asal mazmoon par jayen',
  'Language': 'Zaban',
  'Dark mode': 'Dark mode',
  'Light mode': 'Light mode',
  'Switch to dark mode': 'Dark mode lagayen',
  'Switch to light mode': 'Light mode lagayen',
  'Dark mode enabled.': 'Dark mode on hai.',
  'Light mode enabled.': 'Light mode on hai.',
  'Show {feature}': '{feature} dikhayein',
  'Hide {feature}': '{feature} chhupayein',
  'Customer account metrics': 'Customer account ke hisaab',
  'Cloud billing portal': 'Cloud par billing ka portal',
  'Isolated review edition': 'Alag review nuskha',
  'Setup pending': 'Setup baqi hai',
  'Connect an approved Supabase project': 'Manzoor-shuda Supabase project jorein',
  'This isolated portal has no project credentials configured. Copy .env.example to .env.local and enter only the approved project URL and publishable/anon key. No database connection is attempted until both are present.': 'Is alag portal mein project credentials set nahin hain. .env.example ko .env.local mein copy karein aur sirf manzoor-shuda project URL aur publishable/anon key darj karein. Donon maujood honay tak database connection ki koshish nahin hogi.',
  'Private sign-in': 'Mehfooz sign-in',
  'Sign in to your account': 'Apne account mein sign in karein',
  'Customer usernames and temporary passwords are issued by an authorized Shahdara administrator. Temporary passwords must be changed at first sign-in. Email-invited accounts can sign in with a password or a secure sign-in link. Use Forgot password once to choose an initial password. Self-service sign-up is disabled.': 'Customer usernames aur aarzi passwords sirf ijazat-yafta Shahdara administrator jari karta hai. Pehli martaba sign in par aarzi password tabdeel karna lazmi hai. Email invitation walay accounts password ya mehfooz sign-in link se sign in kar sakte hain. Pehla password chunne ke liye aik martaba password bhoolne ka rasta istemal karein. Khud sign-up band hai.',
  'Customer username sign-in': 'Customer username se sign in',
  'Email and password sign-in': 'Email aur password se sign in',
  'Email address': 'Email address',
  'Username': 'Istemaal ka naam',
  'Password': 'Khufia lafz',
  'Sign in with username': 'Username se sign in karein',
  'Sign in with email and password': 'Email aur password se sign in karein',
  'Forgot password? Send a recovery email': 'Password bhool gaye? Recovery email bhejein',
  'Email or password is incorrect or unavailable.': 'Email ya password ghalat hai ya dastiyab nahin.',
  'Sending a recovery email…': 'Recovery email bheji ja rahi hai…',
  'Recovery email could not be requested. Try again later.': 'Recovery email ki darkhwast nahin ho saki. Baad mein dobara koshish karein.',
  'If this email belongs to an invited account, a recovery email has been requested. Email delivery is not confirmed by this page.': 'Agar yeh email kisi invited account ki hai to recovery email ki darkhwast bhej di gayi hai. Yeh page email delivery ki tasdeeq nahin karta.',
  'Choose a new password': 'Naya password chunein',
  'The recovery link is for this app. Set a password here; future sign-ins can use email and password without another email.': 'Recovery link isi app ke liye hai. Yahan password set karein; agli martaba email aur password se sign in hoga aur doosri email zaroori nahin hogi.',
  'Updating password…': 'Password update ho raha hai…',
  'Password could not be updated. Check the recovery link and try again.': 'Password update nahin ho saka. Recovery link check karke dobara koshish karein.',
  'Recovery link could not be verified or has expired. Request a new one.': 'Recovery link ki tasdeeq nahin ho saki ya is ki muddat khatam ho gayi. Naya link mangain.',
  'Cancel and return to sign in': 'Radd karke sign in par wapas jayen',
  'Could not exit password recovery. Try again.': 'Password recovery se bahar nahin aa sake. Dobara koshish karein.',
  'Password recovery was canceled.': 'Password recovery radd kar di gayi.',
  'Your password was updated successfully.': 'Apka password kamyabi se update ho gaya.',
  'Your password was updated. Sign in with your email and new password.': 'Password update ho gaya. Email aur naye password se sign in karein.',
  'Email sign-in for invited accounts': 'Invite shuda accounts ke liye email sign-in',
  'Customer account security': 'Customer account ki hifazat',
  'Internal staging test accounts sign in with their linked PPPoE username and the initial portal password shared by a Shahdara administrator. Change it at first sign-in before customer data is available.': 'Androoni staging test accounts apne linked PPPoE username aur Shahdara administrator ke diye gaye ibtidai portal password se sign in karein. Customer data milne se pehle pehli martaba password tabdeel karein.',
  'Change your temporary password': 'Apna aarzi password tabdeel karein',
  'Temporary password expired': 'Aarzi password ki muddat khatam',
  'Customer access is temporarily unavailable': 'Customer access aarzi taur par dastiyab nahin',
  'Set a new password before portal data is available. The temporary password can be used only once and expires after 24 hours.': 'Portal data dekhne se pehle naya password banayein. Aarzi password sirf aik martaba istemal ho sakta hai aur 24 ghanton baad khatam ho jata hai.',
  'This temporary password expired or was already used. Ask a Shahdara administrator to issue a new one.': 'Yeh aarzi password khatam ho chuka ya pehle istemal ho gaya. Shahdara administrator se naya password jari karne ko kahein.',
  'Customer data is blocked until an administrator reviews or resets this account.': 'Administrator ke jaize ya reset tak customer data band rahega.',
  'New password': 'Naya password',
  'Confirm new password': 'Naye password ki tasdeeq',
  'Save new password': 'Naya password save karein',
  'The new passwords do not match.': 'Naye passwords aik jaise nahin.',
  'Choose a password between 12 and 72 UTF-8 bytes.': '12 se 72 UTF-8 bytes ke darmiyan password chunein.',
  'Updating password…': 'Password update ho raha hai…',
  'Password could not be changed. Try again or contact an administrator.': 'Password tabdeel nahin ho saka. Dobara koshish karein ya administrator se rabta karein.',
  'Username + temporary password': 'Username + aarzi password',
  'Issue or reset a separate customer username and temporary password. Customer data stays blocked until the password is changed. The password is shown once; closing this profile clears it. The internal synthetic address is not an inbox and never proves inbox ownership.': 'Customer ke liye alag username aur aarzi password jari ya reset karein. Password tabdeel honay tak customer data band rahega. Password sirf aik dafa dikhaya jayega; profile band karne se yeh mit jayega. Androoni banawati address inbox nahin aur inbox ki milkiyat ka saboot nahin.',
  'Internal staging test login': 'Androoni staging test login',
  'Enable only for an internal test customer. It uses this customer’s existing PPPoE username and the default portal password 123456; the customer must change it before any portal data is released. This does not change Overtake, RouterOS, or RADIUS credentials.': 'Sirf androoni test customer ke liye enable karein. Is mein customer ka mojooda PPPoE username aur portal password 123456 istemal hota hai; portal data se pehle customer ko yeh badalna lazmi hai. Overtake, RouterOS ya RADIUS credentials nahin badalte.',
  'Allow PPPoE username sign-in for this staging test account': 'Is staging test account ke liye PPPoE username sign-in ki ijazat dein',
  'Changing this setting blocks old test sessions when disabled; issue a standard credential reset before changing a test mapping.': 'Is setting ko band karne se purane test sessions ruk jate hain; test mapping badalne se pehle mamooli credential reset jari karein.',
  'Link a valid existing PPPoE username of at most 64 characters before enabling test access.': 'Test access enable karne se pehle 64 ya is se kam characters wala mojooda PPPoE username link karein.',
  'Updating staging test access…': 'Staging test access update ho raha hai…',
  'Staging test access is enabled. The initial portal password is 123456; customer data stays blocked until it is changed.': 'Staging test access enable hai. Ibtidai portal password 123456 hai; badalne tak customer data band rahega.',
  'Staging test access is disabled. Existing PPPoE test sign-in is blocked; issue a standard credential reset before restoring access.': 'Staging test access band hai. Mojooda PPPoE test sign-in ruk gaya; access bahal karne se pehle mamooli credential reset jari karein.',
  'Staging test access could not be saved. Verify the staging migration and Admin access, then try again.': 'Staging test access save nahin ho saka. Staging migration aur Admin access ki tasdeeq ke baad dobara koshish karein.',
  'Only organization administrators can update staging test access.': 'Sirf organization administrators staging test access update kar sakte hain.',
  'Disable staging test access before changing the PPPoE username.': 'PPPoE username badalne se pehle staging test access band karein.',
  'Link a valid existing PPPoE username of at most 64 characters before issuing a staging test login.': 'Staging test login jari karne se pehle 64 ya is se kam characters wala mojooda PPPoE username link karein.',
  'This PPPoE username is already assigned to another customer login. Ask an administrator to review the mapping.': 'Yeh PPPoE username pehle hi doosray customer login ko diya gaya hai. Administrator se mapping check karwaein.',
  'Staging test only: share username and password 123456 with this test customer. Their first sign-in must set a new password before portal data is unlocked.': 'Sirf staging test ke liye: is test customer ko username aur password 123456 dein. Portal data khulne se pehle pehli sign-in par naya password banana lazmi hai.',
  'Reason for credential issue or reset': 'Credential jari ya reset karne ki wajah',
  'I verified this customer under the approved staff identity-check process.': 'Main ne manzoor-shuda staff identity-check tareeqay ke mutabiq customer ki tasdeeq ki hai.',
  'Issue or reset temporary password': 'Aarzi password jari ya reset karein',
  'Complete the identity check and enter a valid reason.': 'Identity check mukammal karein aur durust wajah likhein.',
  'This will block customer portal data until a new password is set. Continue?': 'Naya password banne tak customer portal data band rahega. Jari rakhein?',
  'Issuing credentials…': 'Credentials jari ho rahe hain…',
  'Credential issue or reset could not be completed. Contact an administrator before retrying.': 'Credential jari ya reset nahin ho saka. Dobara koshish se pehle administrator se rabta karein.',
  'Show this temporary password to the customer through the approved staff handoff. It will not be shown again.': 'Manzoor-shuda staff tareeqay se yeh aarzi password customer ko dikhayein. Dobara nahin dikhaya jayega.',
  'Temporary password': 'Aarzi password',
  'Expires': 'Muddat khatam',
  'Username or password is incorrect or unavailable.': 'Username ya password ghalat hai ya dastiyab nahin.',
  'Signing in…': 'Sign in ho raha hai…',
  'The first-owner invitation has been sent. The owner must accept it before requesting a secure sign-in link with the invited email address. This page cannot confirm email delivery or acceptance. Self-service sign-up is disabled.': 'Pehle owner ko invitation bheji ja chuki hai. Mehfooz sign-in link mangne se pehle owner ko invitation qabool karni hogi aur wohi invited email istemal karni hogi. Yeh page email delivery ya qabooliyat ki tasdeeq nahin kar sakta. Khud sign-up band hai.',
  'Email me a secure sign-in link': 'Mujhe mehfooz sign-in link email karein',
  'A Shahdara administrator can request a customer portal invitation. This page cannot confirm email delivery.': 'Shahdara administrator customer portal invitation mang sakta hai. Yeh page email delivery ki tasdeeq nahin kar sakta.',
  'Private customer and billing records are protected by Supabase Auth and database row-level security. Customer invitations are managed by the server-side invite-customer function; email delivery is not confirmed here.': 'Customer aur billing records ko Supabase Auth aur database row-level security mehfooz rakhte hain. Customer invitations server-side invite-customer function sambhalta hai; yahan email delivery ki tasdeeq nahin hoti.',
  'Main navigation': 'Bunyadi navigation',
  'Overview': 'Jaiza',
  'Receipts': 'Raseedein',
  'Service incidents': 'Service masail',
  'My account': 'Mera account',
  'Customer': 'Sarif',
  'Sign out': 'Account se niklein',
  'Loading records allowed for this account…': 'Is account ke liye ijazat-shuda records load ho rahe hain…',
  'Could not load records': 'Records load nahin ho sake',
  'Access was not granted': 'Access nahin mila',
  'The request failed.': 'Darkhwast nakam hui.',
  'Database row-level policies remain authoritative; contact the ISP administrator if this account should have portal access.': 'Database row-level policies hi faisla-kun hain; agar is account ko portal access milna chahiye to ISP administrator se rabta karein.',
  'No portal access': 'Portal access nahin hai',
  'Account access is not available': 'Account access dastiyab nahin',
  'Ask the ISP administrator to verify this account or issue an invitation.': 'ISP administrator se is account ki tasdeeq ya invitation jari karne ko kahein.',
  'Account access is not available.': 'Account access dastiyab nahin.',
  'Ask the ISP administrator to assign an Admin role or send a customer invitation.': 'ISP administrator se Admin role dene ya customer invitation bhejne ko kahein.',
  'Sign-in could not be completed': 'Sign-in mukammal nahin ho saka',
  'Account access needs review': 'Account access ka jaiza zaroori hai',
  'Customer portal loaded for': 'Customer portal load hua:',
  'Administrator portal loaded.': 'Administrator portal load ho gaya.',
  'No portal access is linked to this account.': 'Is account ke saath portal access linked nahin hai.',
  'Could not load records.': 'Records load nahin ho sake.',
  'Signed in as': 'Sign in hain:',
  'Customer record': 'Customer record',
  'Dashboard month': 'Dashboard ka mahina',
  'for bill period': 'bill period ke liye',
  'View unpaid bills': 'Baqaya bills dekhein',
  'View unpaid bills for': 'Chunay gaye mahine ke baqaya bills dekhein:',
  'View overdue bills': 'Overdue bills dekhein',
  'View overdue bills for': 'Is mahine ke overdue bills dekhein:',
  'View unpriced bills': 'Baghair price ke bills dekhein',
  'View unpriced bills for': 'Is mahine ke baghair price bills dekhein:',
  'View matching active customers': 'Mutabiq active customers dekhein',
  'View active customers without a bill snapshot for': 'Is mahine bill snapshot ke baghair active customers dekhein:',
  'Clear dashboard filter': 'Dashboard filter hatayein',
  'Dashboard filter cleared.': 'Dashboard filter hata diya gaya.',
  'Showing unpaid bills for {period}. {count} bills match. Unpaid means a priced bill with a positive remaining balance; missing or future due dates are not overdue.': '{period} ke baqaya bills dikhaye ja rahe hain. {count} bills mutabiq hain. Bill ki price record hai aur baqaya raqam zero se zyada hai; ghair-mojood ya aane wali due date overdue nahin hoti.',
  'Showing overdue bills for {period}. {count} bills match. Past-due means an explicitly recorded due date before today and a positive remaining balance.': '{period} ke overdue bills dikhaye ja rahe hain. {count} bills mutabiq hain. Due date wazeh taur par record honi chahiye aur aaj se pehle honi chahiye, aur baqaya bhi baqi ho.',
  'Showing unpriced bills for {period}. {count} bills match. No bill amount is treated as zero.': '{period} ke baghair price bills dikhaye ja rahe hain. {count} bills mutabiq hain. Kisi bill ki raqam ko zero nahin maana gaya.',
  'Showing active customers without a bill snapshot for {period}. {count} customers match.': '{period} ke bill snapshot ke baghair active customers dikhaye ja rahe hain. {count} customers mutabiq hain.',
  'Cash totals follow receipt dates. Credit allocation is shown separately and is never counted as another payment.': 'Cash ka hisaab receipt ki tareekh ke mutabiq hai. Credit allocation alag dikhayi jati hai aur doosri payment nahin gini jati.',
  'Add customer': 'Customer shamil karein',
  'Customer name': 'Customer ka naam',
  'Monthly fee (PKR)': 'Mahawari fee (PKR)',
  'Leave blank if not set': 'Agar tay nahin to khali chhorein',
  'Save customer': 'Customer save karein',
  'Monthly billing': 'Mahawari billing',
  'Create bill snapshot': 'Bill snapshot banayein',
  'Billing Cycle Month': 'Billing cycle ka mahina',
  'Issue Date': 'Jari karne ki tareekh',
  'Exact Due Date': 'Bilkul due tareekh',
  'Choose an exact due date quickly': 'Bilkul due tareekh jaldi chunein',
  'Today': 'Aaj',
  '5th of Month': 'Mahine ki 5 tareekh',
  '10th of Month': 'Mahine ki 10 tareekh',
  'End of Month': 'Mahine ki aakhri tareekh',
  'The issue date starts at today on this device. Due dates are never assumed; month-based choices follow the selected billing cycle.': 'Issue date is device par aaj se shuru hoti hai. Due date khud se nahin maani jati; mahine ke mutabiq intikhab selected billing cycle ke hisaab se hota hai.',
  'Create monthly bill': 'Mahine ka bill banayein',
  'One bill per customer/month. Existing snapshots are returned unchanged. Price corrections are recorded and recalculate derived balances.': 'Har customer ke liye har mahine aik bill. Mojooda snapshot baghair tabdeeli wapas milta hai. Price correction record hoti hai aur balance dobara calculate hota hai.',
  'Invite a customer': 'Customer ko invite karein',
  'Choose an existing active customer and request a portal invitation. This page cannot confirm email delivery. Repeating the same customer and email safely recovers an earlier request without sending a second invitation.': 'Mojooda active customer chunein aur portal invitation mangain. Yeh page email delivery ki tasdeeq nahin kar sakta. Wohi customer aur email dobara dene se pehli request mehfooz tareeqe se wapas milti hai; doosri invitation nahin bheji jati.',
  'Internal staging test accounts can use their saved PPPoE username without an email invitation. Mark only synthetic test accounts in the customer profile; first sign-in still requires a password change.': 'Androoni staging test accounts email invitation ke baghair apna saved PPPoE username istemal kar sakte hain. Customer profile mein sirf synthetic test accounts mark karein; pehli sign-in par password tabdeel karna phir bhi lazmi hai.',
  'Existing customer': 'Mojooda customer',
  'No active customers available': 'Koi active customer dastiyab nahin',
  'Request invitation': 'Invitation mangain',
  'Add an active customer before requesting an invitation.': 'Invitation mangne se pehle active customer shamil karein.',
  'Customer-to-account links remain server-managed and cannot be written from the browser. If a result is uncertain, use the same customer and email to recover; unresolved account states stop for administrator review.': 'Customer-account links server sambhalta hai; browser se likhe nahin ja sakte. Natija wazeh na ho to recovery ke liye wohi customer aur email istemal karein; ghair-wazeh account state administrator ke jaize tak rok di jati hai.',
  'Service username mapping': 'Service username ka link',
  'Link existing PPPoE username': 'Mojooda PPPoE username link karein',
  'Link an existing PPPoE username to a named cloud customer for usage matching only. This does not create a network account or change Overtake, RADIUS, or RouterOS. Never enter a PPPoE password here.': 'Sirf usage matching ke liye mojooda PPPoE username ko cloud customer se link karein. Is se network account nahin banta aur Overtake, RADIUS ya RouterOS nahin badalta. Yahan PPPoE password kabhi darj na karein.',
  'Existing PPPoE username': 'Mojooda PPPoE username',
  'Not linked': 'Link nahin hai',
  'This links the cloud customer record only; the network username and password remain managed by Overtake/RADIUS.': 'Yeh sirf cloud customer record ko link karta hai; network username aur password Overtake/RADIUS sambhalte hain.',
  'Save PPPoE link': 'PPPoE link save karein',
  'Remove PPPoE link': 'PPPoE link hataein',
  'The customers.pppoe_username field is not available in this project yet. Ask the project administrator to review and apply the existing bandwidth-usage migration before linking usernames. No mapping or network credential was changed.': 'Is project mein customers.pppoe_username field abhi dastiyab nahin. Username link karne se pehle project administrator se mojooda bandwidth-usage migration ka jaiza le kar apply karne ko kahein. Koi mapping ya network credential nahin badla.',
  'Existing PPPoE username link saved.': 'Mojooda PPPoE username link save ho gaya.',
  'Existing PPPoE username link removed.': 'Mojooda PPPoE username link hata diya gaya.',
  'Updating PPPoE mapping…': 'PPPoE mapping update ho rahi hai…',
  'Enter an existing PPPoE username or use Remove PPPoE link.': 'Mojooda PPPoE username darj karein ya PPPoE link hataein.',
  'This PPPoE username is already linked to another customer.': 'Yeh PPPoE username pehle se kisi doosray customer ke saath linked hai.',
  'Only organization administrators can update a PPPoE mapping.': 'Sirf organization administrators PPPoE mapping update kar sakte hain.',
  'PPPoE username link could not be saved. Ask the project administrator to verify the mapping schema and your Admin access.': 'PPPoE username link save nahin ho saka. Project administrator se mapping schema aur aap ke Admin access ki tasdeeq karwaein.',
  'Remove the PPPoE link for this customer? Usage matching will stop until a new link is saved.': 'Kya is customer ka PPPoE link hatana hai? Naya link save honay tak usage matching band rahegi.',
  'Record actual receipt': 'Asal receipt record karein',
  'Received on': 'Wasool honay ki tareekh',
  'Amount received (PKR)': 'Wasool raqam (PKR)',
  'Method': 'Tareeqa',
  'Select a method': 'Tareeqa chunein',
  'Cash': 'Naqd',
  'Bank transfer': 'Bank se raqam muntaqili',
  'Other': 'Doosra',
  'Record receipt': 'Receipt record karein',
  'Search customers by name, phone, or Account number': 'Naam, phone ya Account number se customer dhoondein',
  'Search name, phone, or Account #': 'Naam, phone ya Account # dhoondein',
  'Customer portal username is separate from the customer number. Area choices use the saved service address.': 'Customer portal username, customer number se alag hai. Ilaqe ke intikhab mein save-shuda service address istemal hota hai.',
  'Filter customers by payment status or area': 'Payment ki halat ya ilaqe se customers filter karein',
  'All': 'Sab',
  'Area': 'Ilaqa',
  'Filter by saved service address': 'Save-shuda service address se filter karein',
  'Choose an area / address': 'Ilaqa / address chunein',
  'Address not recorded': 'Address record nahin hua',
  'Sort customers': 'Customers ki tartib chunein',
  'Account number (low to high)': 'Account number (kam se zyada)',
  'Name (A to Z)': 'Naam (A se Z)',
  'Outstanding balance (high to low)': 'Baqaya balance (zyada se kam)',
  'Customer directory pages': 'Customers ki fehrist ke safhay',
  'Showing {shownStart}–{shownEnd} of {matching} matching customers; {total} total customers.': 'Kul {total} customers mein se {matching} mutabiq customer entries {shownStart}–{shownEnd} dikhayi ja rahi hain.',
  'No customers match these filters.': 'In filters ke mutabiq koi customer nahin.',
  'Add customer.': 'Customer shamil karein.',
  'Search bills by customer name or Admin phone': 'Customer ke naam ya Admin phone se bills dhoondein',
  'Search customer name or phone': 'Customer ka naam ya phone dhoondein',
  'Phone lookup uses only the Admin-authorized private phone record.': 'Phone lookup sirf Admin ke liye ijazat-shuda private phone record istemal karta hai.',
  'Filter bills by payment status': 'Payment ki halat se bills filter karein',
  'Summary cards above use the selected dashboard month: billed and pending follow bill periods, while collected follows actual receipt dates. Carry-forward credit reduces pending balances but is never counted as cash. WhatsApp opens a draft only; receipts can be printed only from existing receipt records.': 'Upar ke summary cards selected dashboard month istemal karte hain: billed aur pending bill periods ke mutabiq, jabke wasooli asal receipt dates ke mutabiq hai. Carry-forward credit pending balance ghatata hai magar cash nahin gina jata. WhatsApp sirf draft kholta hai; sirf mojooda receipt records print ho sakte hain.',
  'Dated cash entries': 'Tareekh wali cash entries',
  'Actual receipts': 'Asal receipts',
  'Search receipts by customer name, date, method, or amount': 'Customer ke naam, tareekh, tareeqay ya raqam se receipts dhoondein',
  'Search customer, date, method, or amount': 'Customer, tareekh, tareeqa ya raqam dhoondein',
  'Showing {shownStart}–{shownEnd} of {matching} matching receipts; {total} total records.': 'Kul {total} records mein se {matching} mutabiq receipts mein {shownStart}–{shownEnd} dikhayi ja rahi hain.',
  'No receipts match this search.': 'Is search se koi receipt match nahin hui.',
  'Receipt history pages': 'Receipt history ke safhay',
  'Previous page': 'Pichla safha',
  'Next page': 'Agla safha',
  'Page {page} of {pageCount}.': 'Safha {page} / {pageCount}.',
  'Date': 'Tareekh',
  'Amount': 'Raqam',
  'Edit': 'Edit karein',
  'Delete': 'Delete karein',
  'Incident management': 'Service masail ka intizam',
  "Date-times use this device's local time zone. Choose Resolved only when service restoration is confirmed; leave a time blank if it was not recorded.": 'Tareekh aur waqt is device ke local time zone mein hain. Sirf service bahal honay ki tasdeeq par Hal ho gaya chunein; record na kiya gaya waqt khali chhorein.',
  'Affected customer (optional)': 'Mutasira customer (ikhtiyari)',
  'Organization-wide service incident': 'Puri organization ka service masla',
  'Open': 'Jari',
  'Resolved': 'Hal ho gaya',
  'Report service incident': 'Service masla report karein',
  'Recorded incidents': 'Record-shuda masail',
  'Update status and service times': 'Halat aur service ke auqat update karein',
  'Search incidents by customer name or date (YYYY-MM-DD)': 'Customer ke naam ya tareekh (YYYY-MM-DD) se service masail dhoondein',
  'Filter service incidents by status': 'Service masail ko halat ke mutabiq filter karein',
  'Showing {shown} of {matching} matching incidents; {total} total records.': 'Kul {total} records mein se {matching} mutabiq service masail mein {shown} dikhaye ja rahe hain.',
  'No incidents match these filters.': 'In filters se koi service masla nahin mila.',
  'Service incident': 'Service masla',
  'Reported': 'Report hua',
  'Report time not recorded': 'Report ka waqt record nahin',
  'No service incidents are recorded yet.': 'Abhi koi service masla record nahin.',
  'This stored status is outside the supported schema values, so editing is disabled to avoid changing it incorrectly.': 'Save-shuda halat supported schema values se bahar hai; ghalat tabdeeli se bachne ke liye editing band hai.',
  'Save incident update': 'Service maslay ki tabdeeli save karein',
  'Correction': 'Durusti',
  'Edit receipt': 'Receipt edit karein',
  'Original bill': 'Asal bill',
  'Actual amount (PKR)': 'Asal raqam (PKR)',
  'Cancel': 'Radd karein',
  'Save correction': 'Durusti save karein',
  'Explicit correction': 'Wazeh durusti',
  'Correct bill': 'Bill durust karein',
  'Bill amount (PKR)': 'Bill ki raqam (PKR)',
  'Leave blank if not priced': 'Agar price tay nahin to khali chhorein',
  'Dates stay blank when they were not explicitly recorded. Saving updates this bill only.': 'Jo tareekhein wazeh taur par record nahin huin woh khali rahengi. Save karne se sirf yeh bill update hoga.',
  'Save bill correction': 'Bill ki durusti save karein',
  'Customer saved.': 'Customer save ho gaya.',
  'Customer could not be saved.': 'Customer save nahin ho saka.',
  'Choose a valid billing cycle month.': 'Billing cycle ka durust mahina chunein.',
  'Existing monthly snapshot kept unchanged. Use Correct bill to explicitly change its amount or dates.': 'Mojooda mahine ka snapshot baghair tabdeeli rakha gaya. Raqam ya tareekhein wazeh taur par badalne ke liye Bill durust karein istemal karein.',
  'Bill snapshot created. No due date was assumed.': 'Bill snapshot ban gaya. Koi due date khud se nahin maani gayi.',
  'Bill snapshot saved.': 'Bill snapshot save ho gaya.',
  'Bill could not be created.': 'Bill nahin ban saka.',
  'Requesting an invitation…': 'Invitation mangi ja rahi hai…',
  'Supabase Auth rejected the invitation because its email-send rate limit was reached. This request is locked for safe review; ask a Shahdara administrator to check the same customer/email request before any retry. Email delivery is not confirmed.': 'Supabase Auth ne invitation ko email-send rate limit ki wajah se rad kiya. Yeh request mehfooz jaize ke liye lock hai; dobara koshish se pehle Shahdara administrator se isi customer/email request ki jaanch karwaein. Email delivery ki tasdeeq nahin hui.',
  'The invitation result could not be confirmed. Submit the same customer and email again to recover safely; no second invitation will be sent.': 'Invitation ka natija confirm nahin ho saka. Mehfooz recovery ke liye wohi customer aur email dobara submit karein; doosri invitation nahin bheji jayegi.',
  'This customer already has a pending invitation for a different email address. No new invitation was sent. Re-enter the original email to recover it, or ask the organization owner to review the old request before using a new address.': 'Is customer ke liye doosray email address par invitation pehle se pending hai. Nayi invitation nahin bheji gayi. Recovery ke liye asal email dobara darj karein, ya naya address dene se pehle organization owner se purani request check karwaein.',
  'This email address is already reserved by another customer’s unfinished invitation. No new invitation was sent. Ask an organization administrator to check which customer should use it before trying again.': 'Yeh email address doosray customer ki na-mukammal invitation ke liye pehle se reserved hai. Nayi invitation nahin bheji gayi. Dobara koshish se pehle organization administrator se tasdeeq karwaein ke yeh kis customer ka address hai.',
  'The previous invitation could not be safely reconciled. No new invitation was sent. Stop retrying; an organization administrator must review the prior account state before restarting.': 'Pichli invitation ki halat mehfooz tareeqay se clear nahin ho saki. Nayi invitation nahin bheji gayi. Dobara koshish rok dein; restart se pehle organization administrator ko purana account check karna hoga.',
  'The existing invitation state was recovered and linked. No second invitation was sent; email delivery remains unconfirmed.': 'Pehli invitation ki halat recover karke link kar di gayi. Doosri invitation nahin bheji gayi; email delivery ki tasdeeq abhi nahin.',
  'The invitation request was accepted and the account is linked. Email delivery is not confirmed.': 'Invitation ki request qabool hui aur account link ho gaya. Email delivery ki tasdeeq nahin.',
  'Create a bill snapshot before recording a receipt.': 'Receipt record karne se pehle bill snapshot banayein.',
  'Review the actual received date and payment method, then submit the receipt. Nothing has been recorded yet.': 'Asal wasooli ki tareekh aur payment method dekhein, phir receipt submit karein. Abhi kuch record nahin hua.',
  'Receipt recorded. Carry-forward credit is shown separately, not as another payment.': 'Receipt record ho gayi. Carry-forward credit alag dikhayi gayi hai, doosri payment nahin.',
  'Receipt recorded. Carry-forward credit remains separate.': 'Receipt record ho gayi. Carry-forward credit alag hi rahegi.',
  'Receipt could not be recorded.': 'Receipt record nahin ho saki.',
  'Bill correction saved.': 'Bill ki durusti save ho gayi.',
  'Bill could not be corrected.': 'Bill durust nahin ho saka.',
  'Receipt correction saved.': 'Receipt ki durusti save ho gayi.',
  'Receipt correction could not be saved.': 'Receipt ki durusti save nahin ho saki.',
  'Receipt deleted. Any dependent allocations were recalculated.': 'Receipt delete ho gayi. Mutaliqa allocations dobara calculate ki gayi hain.',
  'Delete this cash receipt? Its allocations will be recalculated, and this deletion cannot be undone.': 'Kya yeh cash receipt delete karni hai? Is ki allocations dobara calculate hongi; yeh amal wapas nahin ho sakta.',
  'Allow the print window to open, then choose Print or Save as PDF.': 'Print window khulne dein, phir Print ya Save as PDF chunein.',
  'Bill snapshot created.': 'Bill snapshot ban gaya.',
  'Sending a secure sign-in link…': 'Mehfooz sign-in link bheja ja raha hai…',
  'If this address has an invited account, a sign-in link has been requested. Email delivery is not confirmed by this page.': 'Agar is email ka invited account hai to sign-in link ki request bhej di gayi hai. Yeh page email delivery ki tasdeeq nahin karta.',
  'Sign-in link could not be sent.': 'Sign-in link nahin bheja ja saka.',
  'Archived': 'Archive shuda',
  'Package not set': 'Package tay nahin',
  'Call': 'Call karein',
  'Mark as Paid': 'Paid mark karein',
  'Open profile and billing history for': 'Profile aur billing history kholein:',
  'WhatsApp reminder unavailable;': 'WhatsApp reminder dastiyab nahin;',
  'No bill snapshots have been recorded for this account.': 'Is account ke liye bill snapshots record nahin huay.',
  'No bills match the selected month.': 'Chune gaye mahine mein koi bill nahin.',
  'No cash receipts are recorded for this account.': 'Is account ke liye cash receipts record nahin huin.',
  'Receipt entries are hidden until the date range is corrected.': 'Date range durust karne tak receipt entries chhupi rahengi.',
  'No cash receipts match the selected month and receipt dates.': 'Chune gaye mahine aur receipt dates ke mutabiq cash receipts nahin.',
  'Choose a receipt start date on or before the end date. Receipt entries are hidden until the range is corrected.': 'Receipt ki shuru tareekh, khatam tareekh ke barabar ya us se pehle chunein. Range durust karne tak receipt entries chhupi rahengi.',
  'No bills match this search and status filter.': 'Is search aur halat filter mein koi bill nahin.',
  'Not priced': 'Price tay nahin',
  'Partially paid': 'Kuch raqam ada',
  'Not recorded': 'Record nahin hua',
  'Current balance': 'Mojooda baqaya',
  'Cash received': 'Cash wasool',
  'Plan not set': 'Plan tay nahin',
  'Monthly fee': 'Mahawari fee',
  'Your billing history': 'Aap ki billing history',
  'Bills and receipts': 'Bills aur receipts',
  'Billing / receipt month': 'Billing / receipt ka mahina',
  'Actual cash entries': 'Asal cash entries',
  'Incident timeline': 'Service maslay ka timeline',
  'Recorded service milestones': 'Record-shuda service marahil',
  'No customer-visible service updates are recorded for this account.': 'Is account ke liye customer ko dikhne wali service updates record nahin.',
  'Status not available': 'Halat dastiyab nahin',
  'Time not available': 'Waqt dastiyab nahin',
  'Month not available': 'Mahina dastiyab nahin',
  'Service restored': 'Service bahal hui',
  'Restore': 'Bahal karein',
  'Portal data updated.': 'Portal data update ho gaya.',
  'Refresh failed': 'Refresh nakam hui',
  'Language changed to Roman Urdu.': 'Zaban Roman Urdu kar di gayi.',
  'Language changed to English.': 'Zaban English kar di gayi.',
  'account': 'khata',
  'Billing status': 'Billing ki halat',
  'Admin-only phone': 'Sirf Admin ke liye phone',
  'Service address not recorded': 'Service address record nahin hua',
  'Customer billing history table; scroll horizontally to view all columns': 'Customer billing history table; tamam columns dekhne ke liye side mein scroll karein',
  'Organization-wide': 'Puri organization ka',
  'Unrecognized': 'Na-pehchani hui halat',
  'Billing Month': 'Billing ka mahina',
  'Period not recorded': 'Period record nahin hua',
  'Overdue by': 'Itne din se overdue:',
  'days': 'din',
  'Collect for': 'Wasooli karein:',
  'opens the receipt form without recording payment': 'payment record kiye baghair receipt form kholta hai',
  'Collect': 'Wasool karein',
  'Record a bill price before pre-filling an outstanding amount.': 'Baqaya raqam bharne se pehle bill ki price record karein.',
  'No outstanding balance is recorded.': 'Koi baqaya balance record nahin.',
  'A valid Admin phone and an outstanding priced bill are required.': 'Durust Admin phone aur price wala baqaya bill zaroori hai.',
  'Correct bill for': 'Bill durust karein:',
  'Print or save PDF of the actual receipt for': 'Asal receipt print ya PDF save karein:',
  'Print / Save PDF': 'Print / PDF save',
  'Method not recorded': 'Tareeqa record nahin hua',
  'No actual receipt is recorded against this bill.': 'Is bill ke khilaf asal receipt record nahin.',
  'Issue date not recorded': 'Issue date record nahin hui',
  'Due Date': 'Due tareekh',
  'Due date not recorded': 'Due date record nahin hui',
  'Outstanding': 'Baqaya',
  'Actual receipts linked': 'Linked asal receipts',
  'Carry-forward credit': 'Aglay bill mein muntaqil credit',
  'Bill actions for': 'Bill ke actions:',
  'Actual receipt records': 'Asal receipt records',
  'Total Billed': 'Kul bill',
  'Collected': 'Wasool shuda',
  'Pending': 'Baqaya',
  'priced bill': 'price wala bill',
  'priced bills': 'price walay bills',
  'unpriced excluded': 'baghair price walay shamil nahin',
  'actual receipts by received date; no credit': 'asal receipts wasooli ki tareekh ke mutabiq; credit shamil nahin',
  'actual receipt by received date; no credit': 'asal receipt wasooli ki tareekh ke mutabiq; credit shamil nahin',
  'Outstanding on': 'In bills ka baqaya:',
  'credit applied separately': 'credit alag apply hui',
  'Overdue outstanding balance': 'Muddat guzar chuka baqaya',
  'as of local date': 'device ki local tareekh tak',
  'distinct account': 'alag account',
  'distinct accounts': 'alag accounts',
  'selected bill period; priced bills with a positive balance and a saved due date before today; missing due dates are excluded': 'chuna gaya bill period; price walay bills jin ka baqaya baqi hai aur saved due date aaj se pehle hai; jin ki due date save nahin woh shamil nahin',
  'Unpriced bills': 'Baghair price ke bills',
  'Count only; no bill amount is recorded or treated as zero.': 'Sirf tadaad; bill ki raqam record nahin aur zero nahin samjhi jati.',
  'Active accounts without a bill snapshot': 'Bill snapshot ke baghair active accounts',
  'Active customer accounts with no bill snapshot in this selected month; count only.': 'Chune gaye mahine mein bill snapshot ke baghair active customer accounts; sirf tadaad.',
  'unpriced bill snapshot excluded from billed amount': 'baghair price wala bill snapshot billed amount mein shamil nahin',
  'unpriced bill snapshots excluded from billed amount': 'baghair price walay bill snapshots billed amount mein shamil nahin',
  'Dashboard billing and collection monitoring': 'Dashboard billing aur wasooli ki nigrani',
  'Monthly billing summary': 'Mahinawar billing ka khulasa',
  'not recorded': 'record nahin hua',
  'no Admin phone is recorded': 'Admin phone record nahin',
  'the Admin phone is not a supported Pakistan mobile': 'Admin phone Pakistan ke supported mobile number mein se nahin',
  'the account has no unpaid balance': 'account par koi baqaya nahin',
  'Call unavailable; no Admin phone is recorded': 'Call dastiyab nahin; Admin phone record nahin',
  'Open a prefilled WhatsApp reminder for': 'Pehle se likha WhatsApp reminder kholein:',
  'Mark as Paid: open the receipt form for': 'Paid mark karein: receipt form kholein:',
  'Opens the real receipt form. Nothing is recorded until you review and submit it.': 'Asal receipt form kholta hai. Jaiza le kar submit karne tak kuch record nahin hota.',
  'Quick actions for': 'Jaldi actions:',
  'Close customer profile': 'Customer profile band karein',
  'Monthly bills and their cash receipts, credit, balance, and status.': 'Mahine ke bills, cash receipts, credit, baqaya aur halat.',
  'No bills recorded yet.': 'Abhi koi bill record nahin.',
  'No receipts recorded yet.': 'Abhi koi receipt record nahin.',
  'Cash is counted only from actual receipts; allocations and carry-forward credits reduce balances but are not additional payments.': 'Sirf asal receipts cash mein gini jati hain; allocations aur carry-forward credits baqaya ghatati hain magar izafi payments nahin.',
  'Credit applied': 'Credit apply hui',
  'Customer count, active count, and unpaid count': 'Customers, active aur baqaya accounts ki tadaad',
  'Your account': 'Aap ka account',
  'Total receipts': 'Kul receipts',
  'actual payments': 'asal payments',
  'All months': 'Tamam mahine',
  'Receipt dates from': 'Receipt dates, is tareekh se',
  'Receipt dates through': 'Receipt dates, is tareekh tak',
  'Clear filters': 'Filters saaf karein',
  'Month filters both bill period and receipt date. Start/end dates narrow only the actual receipt list.': 'Mahine ka filter bill period aur receipt date donon par lagta hai. Shuru/khatam tareekhein sirf asal receipts ki fehrist ko mahdood karti hain.',
  'Bill month / plan': 'Bill ka mahina / plan',
  'Bill amount': 'Bill ki raqam',
  'Cash receipts linked to bill': 'Bill se linked cash receipts',
  'Bill balances use the complete allocation history. Actual receipts are counted once; carry-forward credit is separate. A bill without a recorded price has no calculated balance.': 'Bill ka baqaya mukammal allocation history se nikalta hai. Asal receipts aik martaba gini jati hain; carry-forward credit alag hai. Jis bill ki price record nahin us ka balance calculate nahin hota.',
  'Origin bill month': 'Asal bill ka mahina',
  'Amount received': 'Wasool raqam',
  'Receipt date filters apply only to this actual-cash list; they do not change bill balances or credit totals.': 'Receipt date filters sirf is asal-cash fehrist par lagte hain; bill balance ya credit totals nahin badalte.',
  'No milestone times are available.': 'Kisi marhalay ka waqt dastiyab nahin.',
  'Profile not found': 'Profile nahin mili',
  'Ask the ISP administrator to review the account link.': 'ISP administrator se account link ka jaiza lene ko kahein.',
  'In progress': 'Jari hai',
  'Service went offline': 'Service band hui',
  'Restoration recorded': 'Bahal honay ka waqt record hua',
  'Marked resolved; a restoration time is not recorded.': 'Hal ho gaya mark hua; bahali ka waqt record nahin.',
  'Service is marked in progress; a restoration time is not recorded.': 'Service jari mark hai; bahali ka waqt record nahin.',
  'A restoration time is not recorded.': 'Bahali ka waqt record nahin.',
  'Total': 'Kul',
  'Service status': 'Service ki halat',
  'Status': 'Halat',
  'Paid': 'Ada shuda',
  'Unpaid': 'Baqaya',
  'Active': 'Chalu',
  'Offline': 'Band',
  'Not set': 'Tay nahin',
  'No bill yet': 'Abhi bill nahin',
  'Not billed': 'Bill nahin bana',
  'Balance': 'Baqaya',
  'Monthly snapshots': 'Mahinawar snapshots',
  'Customer-visible summary': 'Customer ko dikhne wali tafseel',
  'Service offline at (optional)': 'Service band honay ka waqt (ikhtiyari)',
  'Service restored at (optional)': 'Service bahal honay ka waqt (ikhtiyari)',
  'Staff-only note (optional)': 'Sirf staff ke liye note (ikhtiyari)',
  'Private to same-organization Admins; stored separately and never copied into the customer-visible summary.': 'Sirf isi organization ke Admins ke liye private; alag save hota hai aur customer ko dikhne wali tafseel mein kabhi shamil nahin hota.',
  'No customer records yet.': 'Abhi koi customer record nahin.',
  'Showing {shown} of {total} customers.': 'Kul {total} customers mein se {shown} dikhaye ja rahe hain.',
  'Showing {shown} of {matching} matching bills; {total} total records.': 'Milte-julte {matching} bills mein se {shown} dikhaye ja rahe hain; kul records {total}.',
  'You have signed out.': 'Aap sign out kar chukay hain.',
  'Organization/account': 'Organization / account',
  'Linked customer account': 'Customer ka linked account',
  'Portal navigation': 'Portal ke links',
  'Administrator portal': 'Admin portal',
  'Customer records': 'Customer ke records',
  'Plan / speed': 'Package / speed',
  'Service address': 'Service ka pata',
  'Customer access': 'Customer account access',
  'Email address': 'Email ka pata',
  'Bill': 'Hisab',
  'Customers': 'Sarifeen',
  'Bills': 'Hisabaat',
  'records': 'record',
  'actual receipts': 'asal receipts',
  'Receipts table; scroll horizontally to view all columns': 'Receipts table; tamam columns dekhne ke liye side mein scroll karein',
  'Actual cash receipts with date, customer, method, amount, and available actions.': 'Asal cash receipts: tareekh, customer, tareeqa, raqam aur dastiyab actions.',
  'Actions': 'Kaarwai',
  'Edit receipt for': 'Is customer ki receipt edit karein:',
  'dated': 'tareekh:',
  'Delete receipt for': 'Is customer ki receipt delete karein:',
  'Service operations': 'Service ka kaam',
  'Close': 'Band karein',
  'Plan snapshot not recorded': 'Plan snapshot record nahin hua',
  'Price not recorded; no balance is calculated.': 'Price record nahin hui; balance calculate nahin hota.',
  'Bill month not available': 'Bill ka mahina dastiyab nahin',
  'Bills table; scroll horizontally to view all columns': 'Bills table; tamam columns dekhne ke liye side mein scroll karein',
  'Monthly bill amounts, cash receipts, credit, balance, and status.': 'Mahinawar bill ki raqmein, cash receipts, credit, baqaya aur halat.',
  'shown': 'dikhaye gaye',
  'Actual cash receipts with received date, method, origin bill month, and amount.': 'Asal cash receipts: wasooli ki tareekh, tareeqa, asal bill ka mahina aur raqam.',
  'Customer portal': 'Customer ka portal',
  'Customer profile': 'Customer ki profile',
  'Plan': 'Package',
  'Billing history': 'Billing ka record',
  'Service updates': 'Service ki updates',
  'Customer usage': 'Customer ka internet istemal',
  'Usage dashboard': 'Internet istemal ka jaiza',
  'Service expiry': 'Service ki muddat',
  'Unlimited Package': 'Be-hadd package',
  'Consumed / total quota': 'Istemal shuda / kul quota',
  'Quota consumed': 'Quota ka istemal',
  'consumed': 'istemal shuda',
  'Total used is the sum of download and upload.': 'Kul istemal download aur upload ka majmua hai.',
  'Renewal date:': 'Renewal ki tareekh:',
  'Expiry date not available': 'Expiry ki tareekh dastiyab nahin',
  'The recorded service-expiry date could not be read.': 'Record ki hui service expiry ki tareekh parhi nahin ja saki.',
  'Upcoming renewal': 'Qareeb aati renewal',
  'Expiry warning': 'Expiry ki tanbeeh',
  'Expired': 'Muddat khatam',
  'Renewal in 1 day': 'Renewal 1 din mein',
  'Renewal in {days} days': 'Renewal {days} din mein',
  'Renewal is due today.': 'Aaj renewal due hai.',
  'Renewal is due in 1 day.': 'Renewal 1 din mein due hai.',
  'Renewal is due in {days} days.': 'Renewal {days} din mein due hai.',
  'The renewal date has passed.': 'Renewal ki tareekh guzar chuki hai.',
  'Service expired 1 day ago.': 'Service ki muddat 1 din pehle khatam hui.',
  'Service expired {days} days ago.': 'Service ki muddat {days} din pehle khatam hui.',
  'Expiry date not recorded': 'Expiry ki tareekh record nahin hui',
  'No service-expiry date is recorded for this account. A bill due date is separate and is not used as service expiry.': 'Is account ke liye service expiry ki tareekh record nahin hui. Bill ki due date alag hoti hai; ise service expiry nahin maana jata.',
  'Expiry alerts are unavailable until an actual service-expiry date is recorded.': 'Asal service expiry ki tareekh record honay tak expiry alerts dastiyab nahin.',
  'Usage data could not be loaded. Other account sections are still available.': 'Usage data load nahin hua. Account ke baqi hisay dastiyab hain.',
  'Usage reporting is not linked to this customer profile yet.': 'Usage reporting abhi is customer profile se linked nahin.',
  'No usage snapshot is available yet. Check again after usage reporting is configured.': 'Abhi usage snapshot nahin. Usage reporting set honay ke baad dobara check karein.',
  'Usage values could not be read. Contact your service provider.': 'Usage ki values parhi nahin ja sakin. Apne service provider se rabta karein.',
  'Online': 'Online',
  'Status unavailable': 'Status dastiyab nahin',
  'Quota': 'Data quota',
  'Unlimited': 'Be-hadd',
  'Remaining': 'Baqi',
  'A quota of 0 bytes means unlimited usage.': '0 bytes ka quota be-hadd istemal ka matlab hai.',
  'Remaining quota': 'Baqi quota',
  'remaining': 'baqi',
  'available': 'dastiyab',
  'Usage is over quota by': 'Istemal quota se itna zyada hai',
  'Last synced': 'Aakhri sync',
  'Sync time is not available.': 'Sync ka waqt dastiyab nahin.',
  'This usage snapshot is over 24 hours old; data may be delayed.': 'Yeh usage snapshot 24 ghantay se purana hai; data dair se update ho sakta hai.',
  'Latest cumulative snapshot': 'Aakhri jama-shuda snapshot',
  'Download': 'Download',
  'Upload': 'Upload',
  'Total used': 'Kul istemal',
  'Quota and remaining usage': 'Quota aur baqi data',
  'Cumulative counters only; no billing-period or calendar-month usage history is available.': 'Sirf jama-shuda counters mojood hain; billing period ya calendar month ka usage record dastiyab nahin.',
  'Loading usage and expiry details': 'Usage aur expiry ki tafseel load ho rahi hai.',
  'updates': 'tabdeeliyan',
  'Showing {billShown} of {billTotal} bills and {receiptShown} of {receiptTotal} actual receipts.': '{billTotal} bills mein se {billShown} aur {receiptTotal} asal receipts mein se {receiptShown} dikhaye ja rahe hain.',
  'WhatsApp reminder': 'WhatsApp par yaad-dihani',
  'Account': 'Khata',
  'Package': 'Internet package',
  'Due': 'Aakhri tareekh',
  'bills': 'hisabaat',
  'Customer number': 'Customer ka number',
  'Phone (private)': 'Private phone',
  'Cash ledger': 'Cash ka ledger',
  'Customer directory': 'Customers ki fehrist',
  'Plan snapshot': 'Plan ka snapshot',
  'Service update': 'Service ki update',
  'Admin phone': 'Admin ka phone',
  'Billing period': 'Billing ka period',
  'Period / due': 'Period / due tareekh',
  'Receipt history': 'Receipts ka record',
  'Shahdara Fiber Net · Cloud Portal': 'Shahdara Fiber Net · Cloud par billing portal',
  'Shahdara Fiber Net cloud portal home': 'Shahdara Fiber Net ke cloud portal ka home',
  '03XXXXXXXXX or +923XXXXXXXXX': '03XXXXXXXXX ya +923XXXXXXXXX',
  'Due date:': 'Aakhri tareekh:',
  'Due date set to {date}.': '{date} aakhri tareekh muqarrar kar di gayi.',
  'Cash receipt': 'Naqd ki receipt',
  'Receipt ID:': 'Receipt ki ID:',
  'Billing period linked to receipt': 'Receipt se jura billing period',
  'Actual amount received': 'Asal wasool shuda raqam',
  'Payment method': 'Payment ka tareeqa',
  'Date not recorded': 'Tareekh record nahin hui',
  'Period not available': 'Period dastiyab nahin',
  'Package not recorded': 'Package record nahin hua',
  'This print-ready document reflects an existing cash receipt entry. It does not create a payment or state the remaining bill balance; balances are determined separately from ledger allocations.': 'Yeh print ke liye tayyar document pehle se mojood naqd receipt ko dikhata hai. Yeh payment create nahin karta aur na hi baqaya bill batata hai; balance ledger allocations se alag tay hota hai.',
  'Keep the Receipt ID with your records.': 'Receipt ID apne record ke saath mehfooz rakhein.',
  'Service offline time': 'Service band honay ka waqt',
  'Service restored time': 'Service bahal honay ka waqt',
  '{field} must be a valid local date and time.': '{field} ke liye durust local tareekh aur waqt zaroori hai.',
  'recorded period': 'record hua period',
  'Assalam-o-Alaikum {name}. Shahdara Fiber Net ki {period} ki bill ke hawale se yaad-dihani: outstanding balance {balance} hai.{dueDate} Agar aap payment kar chuke hain to meherbani karke is paigham ko nazar-andaz karein aur humein tasdeeq ke liye rabta karein. Shukriya.': 'Assalam-o-Alaikum {name}. Shahdara Fiber Net ke {period} ke bill ki yaad-dihani: baqaya raqam {balance} hai.{dueDate} Agar aap raqam ada kar chuke hain to meherbani karke is paigham ko nazar-andaz karein aur tasdeeq ke liye hum se rabta karein. Shukriya.',
  'Assalam-o-Alaikum {name}, Shahdara Fiber Net reminder: account #{number} has an unpaid account balance of {balance}{oldest}. If you have already paid, please disregard this reminder and contact us to confirm.': 'Assalam-o-Alaikum {name}, Shahdara Fiber Net ki yaad-dihani: khata #{number} par {balance} baqaya hai{oldest}. Agar aap pehle hi raqam ada kar chuke hain, to meherbani karke is paigham ko nazar-andaz karein aur tasdeeq ke liye hum se rabta karein.',
  ', with the oldest open bill from {period}': '; sab se purana baqaya bill {period} ka hai',
  'Receipt could not be deleted.': 'Receipt delete nahin ho saki.',
  'Receipt could not be recorded. Retry the same receipt with its existing request ID; do not start a second cash entry until the first outcome is clear.': 'Receipt record nahin ho saki. Isi request ID ke saath wahi receipt dobara submit karein; pehli koshish ka natija wazeh honay tak doosri cash entry shuru na karein.',
  '{error} Retry the same receipt with its existing request ID; do not start a second cash entry until the first outcome is clear.': '{error} Isi request ID ke saath wahi receipt dobara submit karein; pehli koshish ka natija wazeh honay tak doosri cash entry shuru na karein.',
  'Customer portal loaded.': 'Customer portal load ho gaya.',
  'Saving incident…': 'Service ka masla save ho raha hai…',
  'Service incident could not be saved.': 'Service ka masla save nahin ho saka.',
  'Service incident marked resolved.': 'Service ka masla hal shuda mark hua.',
  'Service incident reported.': 'Service ka masla report hua.',
  'Service incident updated.': 'Service ke maslay ki tafseel update hui.',
  'Brand identity': 'Company ki shanakht',
  'Company profile': 'Company ka profile',
  'Customers see this name, logo, support phone, and address in their portal and print-ready billing documents.': 'Customers ko portal aur print ke liye billing documents mein yeh naam, logo, support phone aur pata nazar aayega.',
  'The company support phone is separate from each customer’s private phone record.': 'Company ka support phone har customer ke private phone record se alag hai.',
  'Company display name': 'Company ka dikhaya janay wala naam',
  'Support phone': 'Support ka phone',
  'Company address': 'Company ka pata',
  'Logo image': 'Logo ki tasveer',
  'Choose a PNG, JPEG, or WebP image. Maximum size: 1 MB.': 'PNG, JPEG ya WebP tasveer chunein. Zyada se zyada size: 1 MB.',
  'Current company logo': 'Mojooda company logo',
  'No logo uploaded': 'Koi logo upload nahin hua',
  'Save company profile': 'Company profile save karein',
  'Company profile saved.': 'Company profile save ho gaya.',
  'Remove logo': 'Logo hata dein',
  'Your service provider': 'Aap ka service provider',
  'Company profile saved, but it could not be refreshed from the database.': 'Company profile save ho gaya, lekin database se dobara load nahin ho saka.',
  'Company profile saved, but the previous logo could not be removed.': 'Company profile save ho gaya, lekin purana logo nahin hataya ja saka.',
  'Company logo removed.': 'Company logo hata diya gaya.',
  'Check the company name, support phone, and address lengths.': 'Company ke naam, support phone aur pata ki lambai check karein.',
  'Saving company profile…': 'Company profile save ho raha hai…',
  'Company profile could not be saved.': 'Company profile save nahin ho saka.',
  'Remove the company logo?': 'Company logo hata dein?',
  'Print bill': 'Bill print karein',
  'Print or save PDF of this bill': 'Is bill ko print karein ya PDF mein save karein',
  'Bill ID:': 'Bill ki ID:',
  'This print-ready document reflects the saved bill snapshot and currently recorded receipts and credit.': 'Yeh print ke liye tayyar document save-shuda bill snapshot, mojooda receipts aur credit dikhata hai.',
  'Choose a PNG, JPEG, or WebP logo file.': 'PNG, JPEG ya WebP logo file chunein.',
  'The logo must be 1 MB or smaller.': 'Logo ka size 1 MB ya is se kam hona chahiye.',
  'The file contents do not match a PNG, JPEG, or WebP image.': 'File ka content PNG, JPEG ya WebP tasveer se match nahin karta.',
  'The selected logo is not a readable image.': 'Chuna gaya logo parhnay ke qabil tasveer nahin.',
  'Logo dimensions must not exceed 4096 by 4096 pixels.': 'Logo ke dimensions 4096 by 4096 pixels se zyada nahin honay chahiye.',
  'A valid organization and PNG, JPEG, or WebP image are required.': 'Durust organization aur PNG, JPEG ya WebP tasveer zaroori hai.',
  'A secure random logo identifier is required.': 'Mehfooz random logo identifier zaroori hai.',
  'Cashflow and expense tracking': 'Naqd ka bahao aur kharchon ka record',
  'Owner / Admin only': 'Sirf Owner / Admin ke liye',
  'All amounts are PKR. These cash-basis estimates use posted receipts and recorded cash expenses; they are not formal accrual accounts.': 'Tamam raqmein PKR mein hain. Yeh cash-basis andazay jama shuda receipts aur record shuda cash kharchon par mabni hain; yeh formal accrual accounts nahin hain.',
  'Cashflow graph period': 'Cashflow graph ka arsa',
  'month': 'mahina',
  'months': 'mahine',
  'Cash receipts': 'Wasool shuda cash',
  'Operating costs': 'Amli kharchay',
  'Operating profit': 'Amli munafa',
  'Partner distributions': 'Partner ko munafa ki taqseem',
  'Net cashflow after partner distributions': 'Partner taqseem ke baad net cashflow',
  'PKR · selected period': 'PKR · chuna hua arsa',
  'Cashflow chart legend': 'Cashflow graph ki nishaniyan',
  'Cashflow over selected months': 'Chunay huay mahinon ka cashflow',
  'Income includes posted cash receipts only; issued or unpaid bills and allocations are not income. Operating costs exclude partner distributions.': 'Aamdani mein sirf darj shuda cash receipts shamil hain; jari shuda ya unpaid bills aur allocations aamdani nahin. Amli kharchon se partner distributions alag hain.',
  'Zero': 'Sifar',
  'Record a cash expense': 'Naqd kharch record karein',
  'Expense category': 'Kharch ki category',
  'Worker salary': 'Worker ki tankhwa',
  'Nayatel bandwidth': 'Nayatel bandwidth',
  'Partner profit distribution': 'Partner munafa taqseem',
  'Bills (operating costs)': 'Bills (amli kharchay)',
  'Battery / UPS': 'Battery / UPS',
  'Fiber cable': 'Fiber cable',
  'Splitter': 'Splitter',
  'Yellow type': 'Yellow type',
  'White type': 'White type',
  'Black box / fiber joint box': 'Black box / fiber joint box',
  'Amount (PKR)': 'Raqam (PKR)',
  'Optional note': 'Ikhtiyari note',
  'Server-recorded time is UTC and shown in your local time zone.': 'Server par waqt UTC mein record hota hai aur aap ke local time zone mein dikhaya jata hai.',
  'Save cash expense': 'Cash kharch save karein',
  'Searchable expense history': 'Search ki sahulat wala kharchon ka record',
  'Search category, note, or amount': 'Category, note ya raqam search karein',
  'Category': 'Qisam',
  'All categories': 'Tamam categories',
  'From date': 'Is tareekh se',
  'Through date': 'Is tareekh tak',
  'Showing {shown} of {total} matching cash expenses.': '{total} mutabiq cash kharchon mein se {shown} dikhaye ja rahe hain.',
  'Expense history is hidden until the date range is corrected.': 'Tareekhon ka arsa durust honay tak kharchon ka record chhupa hai.',
  'Choose a start date on or before the end date.': 'Shuru ki tareekh khatam ki tareekh ke barabar ya us se pehle chunein.',
  'No recorded expenses match these filters.': 'In filters ke mutabiq koi cash kharch record nahin.',
  'Partner distribution': 'Partner ko munafa ki taqseem',
  'Operating expense': 'Amli kharch',
  'Note': 'Tafseeli note',
  'Cash expense history': 'Cash kharchon ka record',
  'Only same-organization Owners and Admins can record cashflow.': 'Sirf isi organization ke Owners aur Admins cashflow record kar sakte hain.',
  'Cash expense recorded.': 'Cash kharch record ho gaya.',
  'Recording cash expense…': 'Cash kharch record ho raha hai…',
  'Choose a valid expense category.': 'Durust kharch category chunein.',
  'The expense note is too long.': 'Kharch ka note bohat lamba hai.',
  'Customer cash collected and contribution estimate': 'Customer se wasool cash aur contribution ka andaza',
  'Total cash collected from posted receipts': 'Darj shuda receipts se kul wasool cash',
  'Service start date': 'Service shuru honay ki tareekh',
  'Customer record created': 'Customer record bananay ki tareekh',
  'Start date not recorded': 'Shuru honay ki tareekh record nahin',
  'N/A — start date unknown': 'Dastiyab nahin — shuru ki tareekh maloom nahin',
  'Customer tenure': 'Customer ki muddat',
  'year': 'saal',
  'years': 'saal',
  'Less than one month': 'Aik mahine se kam',
  'Estimated customer contribution': 'Customer contribution ka andaza',
  'Unknown — add a start date and an effective monthly cost first.': 'Maloom nahin — pehle shuru ki tareekh aur lagu monthly cost darj karein.',
  'Cost coverage': 'Cost ki coverage',
  'N/A until at least one completed service month has an assigned cost.': 'Jab tak kam az kam aik mukammal service month ki cost darj na ho, dastiyab nahin.',
  'completed service months covered': 'mukammal service months ki cost maujood',
  'months have no recorded cost and are excluded': 'months ki cost record nahin aur shamil nahin',
  'Current incomplete month is excluded; no partial-month proration.': 'Mojooda adhoora mahina shamil nahin; adhooray mahine ki nisbi cost nahin lagti.',
  'Not assigned for this month': 'Is mahine ke liye cost muqarrar nahin',
  'Current assigned monthly package / bandwidth cost': 'Mojooda monthly package / bandwidth cost',
  'Estimate only, not audited net profit. Uses actual posted receipts minus assigned monthly costs for completed service months with recorded effective cost history. Cost allocations are not added to global cash expenses; those count actual bills and outflows only.': 'Sirf andaza hai, audited net profit nahin. Is mein asal receipts se un mukammal service months ki muqarrar monthly cost minus ki jati hai jinki effective cost history record ho. Customer cost allocations global cash expenses mein shamil nahin; un mein asal bills aur outflows hi count hotay hain.',
  'Monthly package / bandwidth cost assignment': 'Monthly package / bandwidth cost muqarrar karein',
  'A new entry is append-only. If entries share an effective month, the latest recorded entry applies and earlier entries remain in the history.': 'Har nayi entry history mein izafa karti hai. Agar aik effective month ki kai entries hon to aakhri record shuda entry lagu hoti hai aur purani entries history mein rehti hain.',
  'Monthly package / bandwidth cost (PKR)': 'Monthly package / bandwidth cost (PKR)',
  'Effective month': 'Lagu honay wala mahina',
  'Monthly package / bandwidth cost': 'Mahwar package / bandwidth ki cost',
  'Recorded at (local time)': 'Local waqt mein record hua',
  'Active for this month': 'Is mahine ke liye lagu',
  'Superseded entry': 'Baad ki entry se tabdeel',
  'Save effective cost entry': 'Lagu cost entry save karein',
  'Effective monthly cost history': 'Monthly cost ki effective history',
  'No service cost history recorded yet.': 'Abhi service cost history record nahin hui.',
  'Saving effective cost history…': 'Lagu cost history save ho rahi hai…',
  'Monthly service-cost history updated.': 'Monthly service cost history update ho gayi.',
  'Choose a valid effective month.': 'Durust lagu honay wala mahina chunein.',
  'The service cost note is too long.': 'Service cost ka note bohat lamba hai.',
  'Service cost could not be confirmed. Retry the same customer, effective month, amount, and note to avoid a duplicate.': 'Service cost ki tasdeeq nahin ho saki. Duplicate se bachne ke liye wahi customer, effective month, raqam aur note dobara istemal karein.',
});

export function normalizeLanguage(value) {
  return value === 'ur-Latn' ? 'ur-Latn' : 'en';
}

export function getStoredLanguage(storage) {
  try {
    const target = storage ?? globalThis.localStorage;
    return normalizeLanguage(target?.getItem(LANGUAGE_STORAGE_KEY));
  } catch {
    return 'en';
  }
}

export function storeLanguage(language, storage) {
  const normalized = normalizeLanguage(language);
  try {
    const target = storage ?? globalThis.localStorage;
    target?.setItem(LANGUAGE_STORAGE_KEY, normalized);
    return Boolean(target);
  } catch {
    return false;
  }
}

export function setLanguagePreference(language, storage, documentObject) {
  const normalized = normalizeLanguage(language);
  const persisted = storeLanguage(normalized, storage);
  applyDocumentLanguage(documentObject, normalized);
  return { language: normalized, persisted };
}

export function applyDocumentLanguage(documentObject, language) {
  const target = documentObject ?? globalThis.document;
  if (!target?.documentElement) return;
  const normalized = normalizeLanguage(language);
  target.documentElement.lang = normalized;
  target.documentElement.dir = 'ltr';
}

export function translateUi(message, language = 'en') {
  if (normalizeLanguage(language) !== 'ur-Latn') return String(message ?? '');
  return ROMAN_URDU[String(message ?? '')] ?? String(message ?? '');
}

export function formatUiMessage(message, language = 'en', values = {}) {
  return translateUi(message, language).replace(/\{([a-zA-Z][a-zA-Z0-9_]*)\}/g, (_match, name) => String(values[name] ?? ''));
}

export function escapeHtml(value) {
  return String(value ?? '').replace(/[&<>"']/g, (character) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  })[character]);
}
